### ISSUE TITLE
Include source on PyPI

### ISSUE THREAD

**Issue by jwillikers** [alexmojaki/outdated#10]
Betwwen versions 0.2.0 and 0.2.1 this package switched from providing a source tarball to a wheel. Would it be possible to still supply the source tarball? The [Flatpak-Pip-Generator](https://github.com/flatpak/flatpak-builder-tools/tree/master/pip) tries to grab the source tarball when compiling dependency data which ends up being a bit of a blocker.

**Comment by alexmojaki** [comment]
Uploaded, let me know if anything is wrong.

**Comment by jwillikers** [comment]
Works great now. Thanks so much for updating this for me!
